update=01/04/2018 16:15:04
version=1
last_client=kicad
[cvpcb]
version=1
NetIExt=net
[pcbnew]
version=1
PageLayoutDescrFile=C:/xesscorp/KiCad/page_layouts/title_block_only.kicad_wks
LastNetListRead=
UseCmpFile=1
PadDrill=0.6
PadDrillOvalY=0.6
PadSizeH=1.5
PadSizeV=1.5
PcbTextSizeV=1.5
PcbTextSizeH=1.5
PcbTextThickness=0.3
ModuleTextSizeV=1
ModuleTextSizeH=1
ModuleTextSizeThickness=0.15
SolderMaskClearance=0
SolderMaskMinWidth=0
DrawSegmentWidth=0.2
BoardOutlineThickness=0.09999999999999999
ModuleOutlineThickness=0.15
[general]
version=1
[eeschema]
version=1
LibDir=C:/xesscorp/KiCad/libraries
[eeschema/libraries]
LibName1=C:/Users/Marco/Documents/Kicad/Kicad/kicad-symbols-master/Device
LibName2=C:/Users/Marco/Documents/Kicad/Kicad/kicad-symbols-master/Diode
LibName3=C:/Users/Marco/Documents/Kicad/Kicad/kicad-symbols-master/Interface
LibName4=C:/Users/Marco/Documents/Kicad/Kicad/kicad-symbols-master/Interface_Expansion
LibName5=C:/Users/Marco/Documents/Kicad/Kicad/kicad-symbols-master/Interface_LineDriver
LibName6=C:/Users/Marco/Documents/Kicad/Kicad/kicad-symbols-master/Interface_USB
LibName7=C:/Users/Marco/Documents/Kicad/Kicad/kicad-symbols-master/Mechanical
LibName8=C:/Users/Marco/Documents/Kicad/Kicad/kicad-symbols-master/power
LibName9=C:/Users/Marco/Documents/Kicad/Kicad/kicad-symbols-master/Relay
LibName10=C:/Users/Marco/Documents/Kicad/Kicad/kicad-symbols-master/Transistor_FET
LibName11=C:/Users/Marco/Documents/Kicad/libraries/Kemet_Relay/ee2-5nu
LibName12=C:/Users/Marco/Documents/Kicad/Kicad/kicad-symbols-master/Connector_Specialized
LibName13=C:/Users/Marco/Documents/Kicad/Kicad/kicad-symbols-master/Connector_Generic
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
